DROP_MOVIE_TABLE = '''DROP TABLE IF EXISTS MOVIES'''

DROP_PROJECTIONS_TABLE = '''DROP TABLE IF EXISTS PROJECTIONS'''

DROP_USERS_TABLE = '''DROP TABLE IF EXISTS USERS'''

DROP_RESERVATIONS_TABLE = '''DROP TABLE IF EXISTS RESERVATIONS'''

CREATE_MOVIES_TABLE = '''
    CREATE TABLE IF NOT EXISTS MOVIES(
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        NAME TEXT NOT NULL,
        RATING DECIMAL(0, 10) NOT NULL
    )
'''

CREATE_PROJECTIONS_TABLE = '''
    CREATE TABLE IF NOT EXISTS PROJECTIONS(
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        MOVIE_ID INTEGER NOT NULL,
        TYPE VARCHAR(3),
        DATE TEXT NOT NULL,
        TIME TEXT NOT NULL,
        FOREIGN KEY(MOVIE_ID) REFERENCES MOVIES(ID)
    )
'''

CREATE_USERS_TABLE = '''
    CREATE TABLE IF NOT EXISTS USERS(
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        USERNAME TEXT NOT NULL,
        PASSWORD TEXT NOT NULL,
        IS_ACTIVE INTEGER NOT NULL DEFAULT 0
    )
'''

CREATE_RESERVATIONS_TABLE = '''
    CREATE TABLE IF NOT EXISTS RESERVATIONS(
        ID INTEGER PRIMARY KEY AUTOINCREMENT
        USER_ID INTEGER  NOT NULL,
        PROJECTION_ID INTEGER NOT NULL,
        ROW INTEGER NOT NULL,
        COL INTEGER NOT NULL,
        FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
        FOREIGN KEY(PROJECTION_ID) REFERENCES PROJECTIONS(ID)
    )
'''

LIST_MOVIES_IDS = ''' SELECT ID FROM MOVIES '''

LIST_USERS_IDS = ''' SELECT ID FROM USERS '''

LIST_ROJECTIONS_IDS = ''' SELECT ID FROM PROJECTIONS '''

LIST_RESERVATIONS_IDS = ''' SELECT ID FROM RESERVATIONS '''

ADD_PROJECTION = '''
    INSERT INTO PROJECTIONS(MOVIE_ID, TYPE, DATE, TIME)
    VALUES(?, ?, ?, ?)
'''

ADD_MOVIE = '''
    INSERT INTO MOVIES(NAME, RATING)
    VALUES(?, ?)
'''

ADD_USER = '''
    INSERT INTO USERS(USERNAME, PASSWORD)
    VALUES(?, ?)
'''

ADD_RESERVATION = '''
    INSERT INTO RESERVATIONS(USER_ID, PROJECTION_ID, ROW, COL)
    VALUES(?, ?, ?, ?)
'''

# ---------------------------------------------------------------------------

LIST_MOVIES_ORDERED_BY_RATING = '''
    SELECT ID, NAME, RATING
    FROM MOVIE
    ORDER BY RATING
'''

MOVIE_PROJECTIONS = '''
    SELECT PR.ID, MOVIE.NAME, PR.TYPE, PR.DATE, PR.TIME
    FROM MOVIE
    LEFT JOIN PROJECTIONS AS PR ON MOVIE.ID == PR.MOVIE_ID
    WHERE MOVIE.ID = ?
'''

MOVIE_PROJECTIONS_ORDERED_BY_DATE = '''
    SELECT PR.ID, MOVIE.NAME, PR.TYPE, PR.DATE, PR.TIME
    FROM MOVIE
    LEFT JOIN PROJECTIONS AS PR ON MOVIE.ID == PR.MOVIE_ID
    WHERE MOVIE.ID = ?
    ORDER BY DATE
'''

COUNT_UNAVAILABLE_SEATS_FOR_PROJECTION = '''
    SELECT COUNT(ID)
    FROM RESERVATIONS
    GROUP BY PROJECTION_ID
    WHERE PROJECTION_ID=?
'''

ID_OF_USER_BY_USERNAME = '''
    SELECT ID
    FROM USERS
    WHERE USERNAME=?
'''

PASSWORD_OF_USER = '''
    SELECT PASSWORD
    FROM USERS
    WHERE ID=?
'''

SEATS_FOR_PROJECTION = '''
    SELECT ROW, COL
    FROM RESERVATIONS
    WHERE PROJECTION_ID=?
'''

DETELE_RESERVATION = '''
    DELETE FROM RESERVATIONS
    WHERE ID=?
'''

DELETE_ALL_RESERVATION_OF_USER = '''
    DELETE FROM RESERVATIONS
    WHERE USER_ID=?
'''
